build: bump node-fetch from 3.2.4 to 3.2.10 (#4794)
Bumps [node-fetch](https://github.com/node-fetch/node-fetch) from 3.2.4 to 3.2.10.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/node-fetch/node-fetch/releases">node-fetch's releases</a>.</em></p>
<blockquote>
<h2>v3.2.10</h2>
<h2><a href="https://github.com/node-fetch/node-fetch/compare/v3.2.9...v3.2.10">3.2.10</a> (2022-07-31)</h2>
<h3>Bug Fixes</h3>
<ul>
<li>ReDoS referrer (<a href="https://github-redirect.dependabot.com/node-fetch/node-fetch/issues/1611">#1611</a>) (<a href="https://github.com/node-fetch/node-fetch/commit/28802387292baee467e042e168d92597b5bbbe3d">2880238</a>)</li>
</ul>
<h2>v3.2.9</h2>
<h2><a href="https://github.com/node-fetch/node-fetch/compare/v3.2.8...v3.2.9">3.2.9</a> (2022-07-18)</h2>
<h3>Bug Fixes</h3>
<ul>
<li><strong>Headers:</strong> don't forward secure headers on protocol change (<a href="https://github-redirect.dependabot.com/node-fetch/node-fetch/issues/1599">#1599</a>) (<a href="https://github.com/node-fetch/node-fetch/commit/e87b093fd678a9ea39c5b17b2a1bdfc4691eedc7">e87b093</a>)</li>
</ul>
<h2>v3.2.8</h2>
<h2><a href="https://github.com/node-fetch/node-fetch/compare/v3.2.7...v3.2.8">3.2.8</a> (2022-07-12)</h2>
<h3>Bug Fixes</h3>
<ul>
<li>possibly flaky test (<a href="https://github-redirect.dependabot.com/node-fetch/node-fetch/issues/1523">#1523</a>) (<a href="https://github.com/node-fetch/node-fetch/commit/11b703361134340a8361f591d6e3a0bcf6a261fa">11b7033</a>)</li>
</ul>
<h2>v3.2.7</h2>
<h2><a href="https://github.com/node-fetch/node-fetch/compare/v3.2.6...v3.2.7">3.2.7</a> (2022-07-11)</h2>
<h3>Bug Fixes</h3>
<ul>
<li>always warn Request.data (<a href="https://github-redirect.dependabot.com/node-fetch/node-fetch/issues/1550">#1550</a>) (<a href="https://github.com/node-fetch/node-fetch/commit/4f43c9ed63da98f4b5167f0a8e447cd0f0133cd3">4f43c9e</a>)</li>
</ul>
<h2>v3.2.6</h2>
<h2><a href="https://github.com/node-fetch/node-fetch/compare/v3.2.5...v3.2.6">3.2.6</a> (2022-06-09)</h2>
<h3>Bug Fixes</h3>
<ul>
<li>undefined reference to response.body when aborted (<a href="https://github-redirect.dependabot.com/node-fetch/node-fetch/issues/1578">#1578</a>) (<a href="https://github.com/node-fetch/node-fetch/commit/1c5ed6b981e6c5dd28bd50f5ab5418e5bd262b99">1c5ed6b</a>)</li>
</ul>
<h2>v3.2.5</h2>
<h2><a href="https://github.com/node-fetch/node-fetch/compare/v3.2.4...v3.2.5">3.2.5</a> (2022-06-01)</h2>
<h3>Bug Fixes</h3>
<ul>
<li>use space in accept-encoding values (<a href="https://github-redirect.dependabot.com/node-fetch/node-fetch/issues/1572">#1572</a>) (<a href="https://github.com/node-fetch/node-fetch/commit/a92b5d5cf4457c2da95d8404b08cfd06a426a2fa">a92b5d5</a>), closes <a href="https://github-redirect.dependabot.com/node-fetch/node-fetch/issues/1571">#1571</a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/node-fetch/node-fetch/commit/28802387292baee467e042e168d92597b5bbbe3d"><code>2880238</code></a> fix: ReDoS referrer (<a href="https://github-redirect.dependabot.com/node-fetch/node-fetch/issues/1611">#1611</a>)</li>
<li><a href="https://github.com/node-fetch/node-fetch/commit/e87b093fd678a9ea39c5b17b2a1bdfc4691eedc7"><code>e87b093</code></a> fix(Headers): don't forward secure headers on protocol change (<a href="https://github-redirect.dependabot.com/node-fetch/node-fetch/issues/1599">#1599</a>)</li>
<li><a href="https://github.com/node-fetch/node-fetch/commit/bcfb71c7d10da252280d13818daab6925e12c368"><code>bcfb71c</code></a> chore: remove triple-slash directives from typings (<a href="https://github-redirect.dependabot.com/node-fetch/node-fetch/issues/1285">#1285</a>) (<a href="https://github-redirect.dependabot.com/node-fetch/node-fetch/issues/1287">#1287</a>)</li>
<li><a href="https://github.com/node-fetch/node-fetch/commit/95165d5480ea0552858679a96c7f4ef001412c1b"><code>95165d5</code></a> fix spelling (<a href="https://github-redirect.dependabot.com/node-fetch/node-fetch/issues/1602">#1602</a>)</li>
<li><a href="https://github.com/node-fetch/node-fetch/commit/11b703361134340a8361f591d6e3a0bcf6a261fa"><code>11b7033</code></a> fix: possibly flaky test (<a href="https://github-redirect.dependabot.com/node-fetch/node-fetch/issues/1523">#1523</a>)</li>
<li><a href="https://github.com/node-fetch/node-fetch/commit/4f43c9ed63da98f4b5167f0a8e447cd0f0133cd3"><code>4f43c9e</code></a> fix: always warn Request.data (<a href="https://github-redirect.dependabot.com/node-fetch/node-fetch/issues/1550">#1550</a>)</li>
<li><a href="https://github.com/node-fetch/node-fetch/commit/1c5ed6b981e6c5dd28bd50f5ab5418e5bd262b99"><code>1c5ed6b</code></a> fix: undefined reference to response.body when aborted (<a href="https://github-redirect.dependabot.com/node-fetch/node-fetch/issues/1578">#1578</a>)</li>
<li><a href="https://github.com/node-fetch/node-fetch/commit/a92b5d5cf4457c2da95d8404b08cfd06a426a2fa"><code>a92b5d5</code></a> fix: use space in accept-encoding values (<a href="https://github-redirect.dependabot.com/node-fetch/node-fetch/issues/1572">#1572</a>)</li>
<li><a href="https://github.com/node-fetch/node-fetch/commit/0f122b882461d0b212ba75dd92f4606e1cb12812"><code>0f122b8</code></a> docs: fix formdata code example (<a href="https://github-redirect.dependabot.com/node-fetch/node-fetch/issues/1562">#1562</a>)</li>
<li><a href="https://github.com/node-fetch/node-fetch/commit/6ae9c7648157ecdf2bc5d3fce2ed61c2256d07e0"><code>6ae9c76</code></a> docs(readme): response.clone() is not async (<a href="https://github-redirect.dependabot.com/node-fetch/node-fetch/issues/1560">#1560</a>)</li>
<li>Additional commits viewable in <a href="https://github.com/node-fetch/node-fetch/compare/v3.2.4...v3.2.10">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=node-fetch&package-manager=npm_and_yarn&previous-version=3.2.4&new-version=3.2.10)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)
You can disable automated security fix PRs for this repo from the [Security Alerts page](https://github.com/quisquous/cactbot/network/alerts).

</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>