build: revert setup-msbuild version change
Error: Unable to resolve action `microsoft/setup-msbuild@v1.1.1`, unable to find version `v1.1.1`

This was broken by the version change in #4892.