build: enable lib check, upgrade @types/node (#4893)
Enabling the lib check has two errors, one in event.d.ts which is easily
fixed. The other is in globby, due to import node:url.

Error:
```
node_modules/copy-webpack-plugin/node_modules/globby/index.d.ts:1:19 - error TS2307: Cannot find module 'node:url' or its corresponding type declarations.
```

This is fixed by upgrading @types/node. Upgraded to the latest version,
not to a specific version.

Closes #4882.
Closes #4885.
Closes #4880.